server:
  port: ${SERVER_PORT:9000}
management:
  server:
    port: ${ACTUATOR_PORT:9001}
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      base-path: ${ACTUATOR_CONTEXT_PATH:/actuator}
      exposure:
        include: info,health,prometheus
spring:
  application:
    name: semefa-gateway
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:semefa}
    username: ${DB_USER:semefa}
    password: ${DB_PASSWORD:semefa}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 8
errors:
  field-error-file: ${FIELD_ERROR_FILE:classpath:error-campo.csv}
  description-error-file: ${DESCRIPTION_ERROR_FILE:classpath:error-descripcion.csv}
mq:
  queue-manager: ${MQ_QUEUE_MANAGER}
  queue-in: ${MQ_QUEUE_IN}
  queue-out: ${MQ_QUEUE_OUT}
  channel: ${MQ_CHANNEL:SYSTEM.DEF.SVRCONN}
  hostname: ${MQ_HOSTNAME:localhost}
  port: ${MQ_PORT:1414}
date:
  time-zone: ${TIME_ZONE:UTC}
jwt:
  issuer: saludaunclic
  expiration-sec: ${JWT_EXPIRATION_SEC:86400}
  clock-skew-sec: ${JWT_CLOCK_SKEW_SEC:300}
  secret: ${JWT_SECRET:changeme}
