-- field_error
INSERT INTO field_error (id, name) VALUES (1, 'Transacción');
INSERT INTO field_error (id, name) VALUES (2, 'ID del remitente o emisor');
INSERT INTO field_error (id, name) VALUES (3, 'ID Receptor');
INSERT INTO field_error (id, name) VALUES (4, 'Fecha');
INSERT INTO field_error (id, name) VALUES (5, 'Hora');
INSERT INTO field_error (id, name) VALUES (6, 'Correlativo');
INSERT INTO field_error (id, name) VALUES (7, 'Identificación única de transacción');
INSERT INTO field_error (id, name) VALUES (8, 'Finalidad');
INSERT INTO field_error (id, name) VALUES (9, 'Calificador del remitente o emisor');
INSERT INTO field_error (id, name) VALUES (010, 'Tipo de Operación');
INSERT INTO field_error (id, name) VALUES (101, 'CODIGO_PAIS_AFILIADO');
INSERT INTO field_error (id, name) VALUES (102, 'TIPO_DOCUMENTO_AFILIADO');
INSERT INTO field_error (id, name) VALUES (103, 'NUMERO_DOCUMENTO_AFILIADO');
INSERT INTO field_error (id, name) VALUES (104, 'NACIONALIDAD_AFILIADO');
INSERT INTO field_error (id, name) VALUES (105, 'AP_PATERNO_AFILIADO');
INSERT INTO field_error (id, name) VALUES (106, 'AP_MATERNO_AFILIADO');
INSERT INTO field_error (id, name) VALUES (107, 'AP_CASADA_AFILIADO');
INSERT INTO field_error (id, name) VALUES (108, 'NOMBRES_AFILIADO');
INSERT INTO field_error (id, name) VALUES (109, 'FECHA_NACIMIENTO_AFILIADO');
INSERT INTO field_error (id, name) VALUES (110, 'UBIGEO_AFILIADO');
INSERT INTO field_error (id, name) VALUES (111, 'GENERO_AFILIADO');
INSERT INTO field_error (id, name) VALUES (112, 'ESTADO_AFILIADO');
INSERT INTO field_error (id, name) VALUES (113, 'FECHA_FALLECIMIENTO_AFILIADO');
INSERT INTO field_error (id, name) VALUES (114, 'FECHA_VALIDACION_RENIEC');
INSERT INTO field_error (id, name) VALUES (115, 'CODIGO_PAIS_TUTOR');
INSERT INTO field_error (id, name) VALUES (116, 'TIPO_DOCUMENTO_TUTOR');
INSERT INTO field_error (id, name) VALUES (117, 'NUMERO_DOCUMENTO_TUTOR');
INSERT INTO field_error (id, name) VALUES (118, 'VINCULO_TUTOR');
INSERT INTO field_error (id, name) VALUES (119, 'CODIGO_PAIS_ACTUALIZAR');
INSERT INTO field_error (id, name) VALUES (120, 'TIPO_DOCUMENTO_ACTUALIZAR');
INSERT INTO field_error (id, name) VALUES (121, 'NUMERO_DOCUMENTO_ACTUALIZAR');
INSERT INTO field_error (id, name) VALUES (122, 'FECHA_ACTUALIZACION_AFILIADO');
INSERT INTO field_error (id, name) VALUES (201, 'CODIGO_INTERNO');
INSERT INTO field_error (id, name) VALUES (202, 'CODIGO_CONTRATO');
INSERT INTO field_error (id, name) VALUES (203, 'CODIGO_PRODUCTO');
INSERT INTO field_error (id, name) VALUES (204, 'ESTADO_AFILIACION');
INSERT INTO field_error (id, name) VALUES (205, 'PARENTESCO');
INSERT INTO field_error (id, name) VALUES (206, 'CODIGO_PAIS_CONTRATANTE');
INSERT INTO field_error (id, name) VALUES (207, 'TIPO_DOCUMENTO_CONTRATANTE');
INSERT INTO field_error (id, name) VALUES (208, 'NUMERO_DOCUMENTO_CONTRATANTE');
INSERT INTO field_error (id, name) VALUES (209, 'CODIGO_UNICO_MULTISECTORIAL');
INSERT INTO field_error (id, name) VALUES (210, 'REGIMEN');
INSERT INTO field_error (id, name) VALUES (211, 'FECHA_ACTUALIZACION_ESTADO');
INSERT INTO field_error (id, name) VALUES (212, 'CAUSAL_BAJA');
INSERT INTO field_error (id, name) VALUES (213, 'TIPO_PLAN_SALUD');
INSERT INTO field_error (id, name) VALUES (214, 'NOMBRE_PRODUCTO');
INSERT INTO field_error (id, name) VALUES (215, 'FECHA_INICIO_AFILIACION');
INSERT INTO field_error (id, name) VALUES (216, 'FECHA_FIN_AFILIACION');
INSERT INTO field_error (id, name) VALUES (217, 'FECHA_INICIO_COBERTURA');
INSERT INTO field_error (id, name) VALUES (218, 'FECHA_FIN_COBERTURA');
INSERT INTO field_error (id, name) VALUES (219, 'TIPO_COBERTURA');
INSERT INTO field_error (id, name) VALUES (220, 'ADSCRIPCION_RENIPRESS');
INSERT INTO field_error (id, name) VALUES (221, 'CODIGO_PAIS_TITULAR');
INSERT INTO field_error (id, name) VALUES (222, 'TIPO_DOCUMENTO_TITULAR');
INSERT INTO field_error (id, name) VALUES (223, 'NUMERO_DOCUMENTO_TITULAR');
INSERT INTO field_error (id, name) VALUES (224, 'FECHA_NACIMIENTO_TITULAR');
INSERT INTO field_error (id, name) VALUES (225, 'TIPO_CONTRATANTE');
INSERT INTO field_error (id, name) VALUES (226, 'NOMBRE_CONTRATANTE');
INSERT INTO field_error (id, name) VALUES (227, 'AP_PATERNO_CONTRATANTE');
INSERT INTO field_error (id, name) VALUES (228, 'AP_MATERNO_CONTRATANTE');
INSERT INTO field_error (id, name) VALUES (229, 'AP_CASADA_CONTRATANTE');
INSERT INTO field_error (id, name) VALUES (230, 'FECHA_NACIMIENTO_CONTRATANTE');
INSERT INTO field_error (id, name) VALUES (231, 'FECHA_ACTUALIZACION');
INSERT INTO field_error (id, name) VALUES (232, 'HORA_ACTUALIZACION');
INSERT INTO field_error (id, name) VALUES (100, 'Representa la combinación de campos que identifica la clave unica de la persona afiliada');
INSERT INTO field_error (id, name) VALUES (200, 'Representa la combinación de campos que identifica la clave unica de cada afiliación que cuenta un afiliado');
INSERT INTO field_error (id, name) VALUES (300, 'Representa la combinación de campos que identifica la identificación del tutor');
INSERT INTO field_error (id, name) VALUES (400, 'Representa la combinación de campos que identifica la identificacion del afiliado a actualizar');
INSERT INTO field_error (id, name) VALUES (600, 'Representa la combinación de campos que identifica la identificacion del titular');
INSERT INTO field_error (id, name) VALUES (700, 'Representa la combinación de campos que identifica la Fecha de validación con Reniec con Fecha de actualización');
INSERT INTO field_error (id, name) VALUES (800, 'Representa la combinación de campos que identifica la Fecha de inicio de Afiliación con Fecha de fin de Afiliación');
INSERT INTO field_error (id, name) VALUES (900, 'Representa la combinación de campos que identifica la Fecha de inicio de Latencia con Fecha de fin de Latencia');

-- field_error_rule
INSERT INTO field_error_rule (id, description) values(0, 'Error general no especificado');
INSERT INTO field_error_rule (id, description) values(1, 'Validar que el campo sea requerido');
INSERT INTO field_error_rule (id, description) values(2, 'Validar el tamaño  definido del campo');
INSERT INTO field_error_rule (id, description) values(3, 'Validar el tipo definido del campo.');
INSERT INTO field_error_rule (id, description) values(4, 'Validar que el código de País guarde relacion con el tipo de documento');
INSERT INTO field_error_rule (id, description) values(5, 'Validar que el tamaño del número de documento sea la que corresponda');
INSERT INTO field_error_rule (id, description) values(6, 'El Apellido Paterno del afiliado es requerido siempre en cuando los campos del  apellido paterno y materno también son vacíos.');
INSERT INTO field_error_rule (id, description) values(7, 'Validar la fecha en un rango de 1900 hasta 2050');
INSERT INTO field_error_rule (id, description) values(8, 'Validar la hora HHMMSS ');
INSERT INTO field_error_rule (id, description) values(9, 'Valida que el datos existe en la tabla maestra de paises');
INSERT INTO field_error_rule (id, description) values(10, 'Valida que el datos existe en la tabla maestra de tipos de documentos');
INSERT INTO field_error_rule (id, description) values(11, 'Valida la identidad de la persona ');
INSERT INTO field_error_rule (id, description) values(12, 'Valida que el datos existe en la tabla maestra de ubigeos');
INSERT INTO field_error_rule (id, description) values(13, 'Valida que el datos existe en la tabla maestra de generos');
INSERT INTO field_error_rule (id, description) values(14, 'Valida que el datos existe en la tabla maestra de códigos de indicador de fallecido');
INSERT INTO field_error_rule (id, description) values(15, 'Valida que el datos existe en la tabla maestra de códigos de régimen del afiliado');
INSERT INTO field_error_rule (id, description) values(16, 'Valida que el datos existe en la tabla maestra de códigos de estados del afiliado');
INSERT INTO field_error_rule (id, description) values(17, 'Valida que el datos existe en la tabla maestra de códigos de causales de baja');
INSERT INTO field_error_rule (id, description) values(18, 'Valida que el datos existe en la tabla maestra de códigos de plan de salud peas');
INSERT INTO field_error_rule (id, description) values(19, 'Valida que el datos existe en la tabla maestra de códigos interno del producto');
INSERT INTO field_error_rule (id, description) values(20, 'Valida que el datos existe en la tabla maestra de códigos interno de la cobertura');
INSERT INTO field_error_rule (id, description) values(21, 'Valida que el datos existe en la tabla maestra de códigos del parentesco de afiliado');
INSERT INTO field_error_rule (id, description) values(22, 'Valida que el datos existe en la tabla maestra de códigos del Renipress del afiliado');
INSERT INTO field_error_rule (id, description) values(23, 'Valida que el datos existe en la tabla maestra de códigos del tipos de contratante ');
INSERT INTO field_error_rule (id, description) values(24, 'Valida datallada de datos personales del afiiado con la Reniec');
INSERT INTO field_error_rule (id, description) values(25, 'Valida persona fallecida con la Reniec');
INSERT INTO field_error_rule (id, description) values(26, 'Valida clave de persona a actualizar exista en el padron de afiliados');
INSERT INTO field_error_rule (id, description) values(27, 'Valida que exista el titular de un afiliación familiar');
INSERT INTO field_error_rule (id, description) values(28, 'Valida de fechas inicio y fin de afiliación e inicio y fin de cobertura');
INSERT INTO field_error_rule (id, description) values(29, 'Valida la clave de la identificación de una afiliación dependiendo de la operación');
INSERT INTO field_error_rule (id, description) values(30, 'Validar régimen por IAFAS');
INSERT INTO field_error_rule (id, description) values(31, 'Validar plan de salud por IAFAS');
INSERT INTO field_error_rule (id, description) values(32, 'Evaluar el campo estado de alta');
INSERT INTO field_error_rule (id, description) values(33, 'Evaluar el campo estado de actualizacion');
INSERT INTO field_error_rule (id, description) values(34, 'Evaluar el campo estado de baja');
INSERT INTO field_error_rule (id, description) values(35, 'Verifica la IAFAS');
INSERT INTO field_error_rule (id, description) values(36, 'Valida que no existe el Código Multiserctorial');
INSERT INTO field_error_rule (id, description) values(37, 'Evaluar el estado de baja de una persona fallecida');
INSERT INTO field_error_rule (id, description) values(38, 'Valida si la IAFAS esta permitido transaccional via online ');
INSERT INTO field_error_rule (id, description) values(39, 'Valida que se envie 0 ó 1, referencia ID(29) de especificaciones técnicas');
INSERT INTO field_error_rule (id, description) values(40, 'Valida que se envie 0 ó 1, referencia ID(71) de especificaciones técnicas');
INSERT INTO field_error_rule (id, description) values(41, 'Valida que el Afiliado no cuente con derechohabientes activos');
INSERT INTO field_error_rule (id, description) values(42, 'Valida que el Afiliado no cuente con otras afiliaciónes activas');
INSERT INTO field_error_rule (id, description) values(43, 'Valida que la Fecha de Validación con Reniec sea anterior a la Fecha de Proceso(Actualización)');
INSERT INTO field_error_rule (id, description) values(44, 'Valida que los datos del Titular correspondan al Parentesco');