version: "3.7"

services:

  semefa-gateway:
    image: vicozizou/semefa-gateway:latest
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      SERVER_PORT:
      ACTUATOR_PORT:
      DB_HOST:
      DB_PORT:
      DB_NAME:
      DB_USER:
      DB_PASSWORD:
      MQ_QUEUE_MANAGER:
      MQ_QUEUE_IN:
      MQ_QUEUE_OUT:
      MQ_CHANNEL:
      MQ_HOSTNAME:
      MQ_PORT:
      JWT_SECRET:
